### ISSUE TITLE
Crash at the Crossroads 9/8/16 Analysis

### ISSUE THREAD

**Issue by smallnamespace** [HearthSim/replay-analysis#1]
Notes

@mrkent

**Comment by smallnamespace** [comment]
http://imgur.com/a/kD0N1

http://imgur.com/a/ZNL9p
http://imgur.com/a/tcGaf

**Comment by mrkent** [comment]
@smallnamespace Could you upload the script to convert crossroads_crash_brawl.py output to the one you sent me last week?

@jleclanche Do you have the full data set?

**Comment by smallnamespace** [comment]
Yes, I'll clean up my scripts and upload them later

**Comment by jleclanche** [comment]
@mrkent yeah I have the full set, we already posted about this brawl though, we're looking at Top 3 already working on preliminary data.

**Comment by jleclanche** [comment]
Closing since the post is out.
